#!/bin/sh

echo 'Bootstrap cluster...'

if [ ! -f insecure_key ]; then
  curl -o insecure_key -fSL https://github.com/phusion/baseimage-docker/raw/master/image/insecure_key
  chmod 600 insecure_key
fi

if [ ! -d .bundle ]; then
  bundle install --path vendor/bundle --binstubs .bundle/bin
fi

if [ ! -d mpi/chef-repo/cookbooks ]; then
  cd mpi/chef-repo
  bundle exec berks vendor cookbooks
  cd ../..
fi

if [ ! -d nfs/chef-repo/cookbooks ]; then
  cd nfs/chef-repo
  bundle exec berks vendor cookbooks
  cd ../..
fi

if [ ! -f Vagrantfile ]; then
  ruby ./script/make_vagrantfile.rb
fi
